on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
name: deploy-client
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the code
      uses: actions/checkout@v3
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        push: true
        tags: ${{ secrets.DOCKER_HUB_USER }}/blog_client:latest


  # deploy:
  #   runs-on: ubuntu-20.04
  #   needs: [build]
  #   steps:
  #   - name: Deploy on digital ocean
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.DO_KEY }}
  #       port: ${{ secrets.PORT }}
  #       script: |
          